plugins {
    id 'application'
}

dependencies {
    implementation 'info.picocli:picocli:4.7.6'
    annotationProcessor 'info.picocli:picocli-codegen:4.7.6'
    implementation 'org.xerial:sqlite-jdbc:3.46.1.3'
    implementation 'com.google.code.gson:gson:2.11.0'
}

application {
    applicationName = 'pmconsole'
    mainClass = 'com.upland.connect.pm.console.PmConsoleMain'
}

tasks.named('run') {
    workingDir = rootProject.projectDir
}
