rootProject.name = 'afp-converter'

include 'afp-api', 'afp-engine', 'afp-cli', 'pm-tools', 'pm-console'

project(':afp-api').projectDir = file('product/afp-api')
project(':afp-engine').projectDir = file('product/afp-engine')
project(':afp-cli').projectDir = file('product/afp-cli')
project(':pm-tools').projectDir = file('management/pm-tools')
project(':pm-console').projectDir = file('management/pm-console')
