-- PM operational rule tables.
-- Mutable operational rules belong here instead of repeatedly mutating AI-POLICY.md.

create table if not exists policy_rule_catalog (
  rule_id text primary key,
  realm text not null default '',
  category text not null default '',
  rule_text text not null default '',
  source_ref text not null default '',
  mutable_by text not null default '',
  enabled integer not null default 1,
  updated_at text not null
);

create table if not exists pm_data_dictionary (
  object_name text primary key,
  object_type text not null default '',
  realm text not null default '',
  definition text not null default '',
  source_ref text not null default '',
  naming_pattern text not null default '',
  updated_at text not null
);

delete from policy_rule_catalog;
delete from pm_data_dictionary;

insert into policy_rule_catalog(rule_id, realm, category, rule_text, source_ref, mutable_by, enabled, updated_at) values
  ('PM-EXEC-001', 'pm', 'execution-defaults', 'Environment preflight is mandatory and runs before application execution: ensure PM console live daemon, verify PID/log health, persist status to SQL knowledge, then execute preview and PM console status unless human overrides.', 'build.gradle:pmEnvironmentPreflight;build.gradle:pmEnvironmentKnowledgeEvidence;AI-POLICY.md#Default execution coupling', 'human', 1, current_timestamp),
  ('PM-REALM-001', 'pm', 'realm-separation', 'PM state databases must be under management/pm/state only.', 'build.gradle:enforcePmApplicationRealmSeparation', 'human', 1, current_timestamp),
  ('PM-REALM-002', 'pm', 'realm-separation', 'PM reports must be under management/pm/reports and must not be emitted into product/afp-converter/preview/.', 'build.gradle:enforcePmApplicationRealmSeparation', 'human', 1, current_timestamp),
  ('PM-GATE-001', 'pm', 'quality-gates', 'qualityGate must include enforceProjectBoundaries.', 'build.gradle:qualityGate', 'human', 1, current_timestamp),
  ('PM-GATE-002', 'pm', 'quality-gates', 'qualityGate must include enforceManagedTooling.', 'build.gradle:qualityGate', 'human', 1, current_timestamp),
  ('PM-GATE-003', 'pm', 'quality-gates', 'qualityGate must include enforcePmApplicationRealmSeparation.', 'build.gradle:qualityGate', 'human', 1, current_timestamp),
  ('PM-PROD-001', 'application', 'release-boundary', 'prodBuild packages application modules only and excludes PM modules.', 'build.gradle:prodBuild', 'human', 1, current_timestamp),
  ('PM-DOC-001', 'pm', 'documentation-cycle', 'documentationManifest must include PM state/report artifacts.', 'build.gradle:documentationManifest', 'human', 1, current_timestamp);
insert into policy_rule_catalog(rule_id, realm, category, rule_text, source_ref, mutable_by, enabled, updated_at) values
  ('PM-ROLLUP-001', 'pm', 'boilerplate-promotion', 'Any framework/process/policy/build mutation must include an updated boilerplate roll-up package under product/boilerplate/update-packages/pz-boilerplate-intelliJ in the same change set.', 'build.gradle:enforceBoilerplateRollupForFrameworkChanges', 'human', 1, current_timestamp),
  ('PM-REALM-003', 'boilerplate', 'realm-separation', 'Boilerplate transfer packages must be maintained under product/boilerplate/update-packages and tracked through boilerplate-state SQL tables as a dedicated third realm.', 'pm-tools:StateDatabaseTool/package_candidates.realm', 'human', 1, current_timestamp);
insert into policy_rule_catalog(rule_id, realm, category, rule_text, source_ref, mutable_by, enabled, updated_at) values
  ('PM-WF-001', 'pm', 'workflow-normalization', 'PM process sequencing should be defined in management/pm/workflow/workflow-manifest.json and consumed by adapter interfaces.', 'management/pm/workflow/workflow-manifest.json', 'human', 1, current_timestamp),
  ('PM-WF-002', 'pm', 'workflow-normalization', 'Gradle adapter must expose normalized PM workflow interface tasks that resolve phases from workflow manifest.', 'build.gradle:pmWorkflowRun', 'human', 1, current_timestamp),
  ('PM-NS-001', 'pm', 'namespace-governance', 'First-party Java package roots must use solutions.pointzero.symphony and must not use com.upland.connect in active source/build/policy scope.', 'build.gradle:enforceNamespaceRoot', 'human', 1, current_timestamp),
  ('PM-COMMS-001', 'pm', 'communication-governance', 'Assistant responses must end with a concise list of the next 10 prioritized tasks.', 'management/pm/policy/policy-rule-tables.sql', 'human', 1, current_timestamp),
  ('PM-NAME-001', 'pm', 'naming-governance', 'Presentation-facing references for constitutional/governance/release artifacts must use human-friendly names and not raw internal token IDs.', 'pm-tools:StateDatabaseTool/humanReadableRef;build.gradle:versionStamp', 'human', 1, current_timestamp),
  ('PM-NAME-002', 'pm', 'naming-governance', 'Presentation-facing event/release references must encode context in the form <what>|<when>|<occurrence> while preserving internal IDs for storage and joins.', 'pm-tools:StateDatabaseTool/humanReadableRef;build.gradle:versionStamp', 'human', 1, current_timestamp),
  ('PM-ID-001', 'pm', 'identifier-governance', 'Any identifier created across project management, policy management, version control, or code workflows must be persisted in SQL identifier_registry.', 'pm-tools:StateDatabaseTool/identifier_registry', 'human', 1, current_timestamp),
  ('PM-ID-002', 'pm', 'identifier-governance', 'PM refresh pipeline must publish management/pm/reports/identifier-registry.json for auditability of persisted identifiers.', 'build.gradle:identifierRegistryReport', 'human', 1, current_timestamp),
  ('PM-SQLCODE-001', 'pm', 'sql-code-index', 'Maintain separate SQL code-index/token-dictionary databases for application, pm, and boilerplate realms.', 'build.gradle:realmCodeDatabases', 'human', 1, current_timestamp),
  ('PM-SQLCODE-002', 'pm', 'sql-code-index', 'Cross-realm keyword swatch changes must use token-dictionary/code-token search workflows.', 'build.gradle:realmTokenSearch', 'human', 1, current_timestamp),
  ('PM-SQLCODE-003', 'pm', 'sql-code-index', 'Build flows must materialize realm-managed source files from SQL before compilation.', 'build.gradle:realmSourcesExport', 'human', 1, current_timestamp),
  ('PM-SQLCODE-004', 'pm', 'sql-code-index', 'Direct filesystem drift from SQL-managed content must be blocked by SQL authority checks in strict mode.', 'build.gradle:sqlAuthorityDriftCheck', 'human', 1, current_timestamp),
  ('PM-SQLCODE-005', 'pm', 'sql-code-index', 'Each realm must publish SQL coverage reports proving managed file index completeness.', 'build.gradle:sqlCoverageReport', 'human', 1, current_timestamp),
  ('PM-SQLCODE-006', 'pm', 'sql-code-index', 'Quality gate must verify SQL reconstruction into a clean temp root before release.', 'build.gradle:sqlReconstructionCheck', 'human', 1, current_timestamp),
  ('PM-CI-001', 'pm', 'ci-governance', 'CI must run SQL-first pre-build integrity checks (via management/tools/recovery_quick_check.sh or equivalent) before Gradle build steps.', '.github/workflows/ci.yml', 'human', 1, current_timestamp),
  ('PM-CI-002', 'pm', 'ci-governance', 'CI should publish recovery/integrity artifacts for troubleshooting and rollback traceability.', '.github/workflows/ci.yml', 'human', 1, current_timestamp),
  ('PM-CI-003', 'pm', 'ci-governance', 'CI and package workflows must block transient SQLite artifacts (.sqlite-wal/.sqlite-shm) from tracked files and exported payloads.', '.github/workflows/ci.yml;management/tools/validate_boilerplate_package.sh;management/tools/export_boilerplate_package.sh', 'human', 1, current_timestamp),
  ('PM-BOILER-001', 'boilerplate', 'promotion-governance', 'Boilerplate package promotion state must be exported from SQL to management/pm/reports/boilerplate-promotion-status.json for review sequencing.', 'build.gradle:boilerplatePromotionReport', 'human', 1, current_timestamp),
  ('PM-DECISION-001', 'pm', 'decision-governance', 'Cross-realm prioritization must be derived from SQL-backed decision logs in each realm database and exported to management/pm/reports/decision-priority-queue.json.', 'build.gradle:decisionPriorityReport', 'human', 1, current_timestamp),
  ('PM-DECISION-002', 'boilerplate', 'decision-governance', 'Boilerplate reasoning must support sub-boilerplate granularity using scope_level/scope_ref/sub_scope_ref in decision_log.', 'pm-tools:StateDatabaseTool/decision_log', 'human', 1, current_timestamp),
  ('PM-KB-001', 'pm', 'knowledge-governance', 'Project reasoning outcomes must be captured in the SQL knowledge base with linked evidence artifacts and decision references.', 'pm-tools:StateDatabaseTool/knowledge_entries', 'human', 1, current_timestamp),
  ('PM-KB-002', 'pm', 'knowledge-governance', 'PM refresh pipeline must publish management/pm/reports/knowledge-base.json from project-state SQLite.', 'build.gradle:knowledgeBaseReport', 'human', 1, current_timestamp),
  ('PM-KB-003', 'pm', 'knowledge-governance', 'PM refresh pipeline must mirror project knowledge into each realm DB and publish realm knowledge sync diagnostics.', 'build.gradle:realmKnowledgeSync', 'human', 1, current_timestamp),
  ('PM-KB-004', 'pm', 'knowledge-governance', 'PM refresh pipeline must evaluate unresolved realm knowledge->decision links and publish gate status output (warn by default, fail in strict mode).', 'build.gradle:realmKnowledgeLinkGate', 'human', 1, current_timestamp),
  ('PM-REASON-001', 'pm', 'reasoning-governance', 'Reasoning experience and derived-knowledge databases must be rebuilt from project-state knowledge during PM refresh.', 'build.gradle:reasoningDatabases', 'human', 1, current_timestamp),
  ('PM-REASON-002', 'pm', 'reasoning-governance', 'PM refresh pipeline must publish management/pm/reports/reasoning-drive.json as current reasoning signal output.', 'management/tools/reasoning_sync.py', 'human', 1, current_timestamp),
  ('PM-CONSOLE-001', 'pm', 'console-governance', 'Console screens must emit standard payload envelopes using exchange format pm-console-screen@1.', 'management/docs/PM_CONSOLE_EXCHANGE_FORMAT.md', 'human', 1, current_timestamp),
  ('PM-CONSOLE-002', 'pm', 'console-governance', 'pmconsole live must be command-driven (REPL style) and should not auto-refresh without explicit command invocation.', 'pm-console:PmConsoleMain.LiveCommand', 'human', 1, current_timestamp),
  ('PM-CONSOLE-003', 'pm', 'console-governance', 'When a human asks to launch/open the console, launch a visible desktop terminal session (not background daemon only) and verify launch response in the same turn.', 'osascript Terminal launch workflow', 'human', 1, current_timestamp),
  ('PM-CONSOLE-004', 'pm', 'console-governance', 'Local execution flows must verify a visible PM console session is running (window + process) before non-environment phases proceed.', 'build.gradle:pmConsoleVisibleCheck', 'human', 1, current_timestamp),
  ('PM-CONSOLE-005', 'pm', 'console-governance', 'Duplicate stale background pmconsole live sessions must be detected and reported each environment cycle, with cleanup task support.', 'management/tools/pm_console_cleanup.py;build.gradle:pmConsoleCleanupStaleSessions', 'human', 1, current_timestamp),
  ('PM-CONSOLE-006', 'pm', 'console-governance', 'Visible PM console launch command must be available as an explicit task for manual recovery (`pmConsoleVisibleLaunch`).', 'build.gradle:pmConsoleVisibleLaunch', 'human', 1, current_timestamp),
  ('PM-ENV-001', 'pm', 'environment-governance', 'Environment health is top-priority and must be checked before any non-environment workflow phase.', 'build.gradle:pmEnvironmentPreflight', 'human', 1, current_timestamp),
  ('PM-ENV-002', 'pm', 'environment-governance', 'PM console PID/running health snapshots must be persisted in SQL knowledge with evidence artifact linkage each cycle.', 'build.gradle:pmEnvironmentKnowledgeSync;build.gradle:pmEnvironmentKnowledgeEvidence', 'human', 1, current_timestamp),
  ('PM-ENV-003', 'pm', 'environment-governance', 'PM console visibility context (visible session PIDs and terminal window IDs) must be persisted in SQL knowledge with linked evidence.', 'build.gradle:pmConsoleVisibilityKnowledgeSync;build.gradle:pmConsoleVisibilityKnowledgeEvidence', 'human', 1, current_timestamp),
  ('PM-ENV-004', 'pm', 'environment-governance', 'Environment governance mode supports strict and relaxed behavior via ENV_GOVERNANCE_MODE; strict is default locally.', 'build.gradle:pmConsoleVisibleCheck', 'human', 1, current_timestamp),
  ('PM-ENV-005', 'pm', 'environment-governance', 'Visible-console enforcement must be CI-safe: in CI/headless mode visibility requirement is disabled while daemon and report checks remain active.', 'build.gradle:pmConsoleVisibleCheck', 'human', 1, current_timestamp),
  ('PM-ENV-006', 'pm', 'environment-governance', 'Environment health reports must pass schema validation in local and CI workflows before publication.', 'build.gradle:environmentHealthSchemaCheck;.github/workflows/ci.yml', 'human', 1, current_timestamp),
  ('PM-ENV-007', 'pm', 'environment-governance', 'Console session identity (terminal window/tab) must be persisted as dedicated knowledge for deterministic session correlation.', 'build.gradle:pmConsoleSessionIdentityKnowledgeSync', 'human', 1, current_timestamp),
  ('PM-ENV-008', 'pm', 'environment-governance', 'Stale-session persistence warnings must be computed from history with configurable thresholds.', 'management/tools/pm_console_cleanup.py --warn-threshold', 'human', 1, current_timestamp),
  ('PM-ENV-009', 'pm', 'environment-governance', 'Stale history schema must be validated before report publication and quality gates.', 'build.gradle:staleHistorySchemaCheck;.github/workflows/ci.yml', 'human', 1, current_timestamp),
  ('PM-ENV-010', 'pm', 'environment-governance', 'Environment policy/default definitions across build and policy docs must pass consistency linting.', 'build.gradle:environmentPolicyDefaultsLint', 'human', 1, current_timestamp),
  ('PM-ENV-011', 'pm', 'environment-governance', 'Compact environment dashboard report must be generated each cycle for quick triage.', 'build.gradle:pmEnvironmentDashboardReport', 'human', 1, current_timestamp),
  ('PM-ENV-012', 'pm', 'environment-governance', 'Governance/release rollout identifiers must be persisted in identifier_registry with human-readable refs.', 'build.gradle:pmPersistGovernanceIdentifiers', 'human', 1, current_timestamp),
  ('PM-SEC-001', 'pm', 'security-governance', 'Console database federation must be constrained to aliases in management/pm/security/authorized-databases.json.', 'management/pm/security/authorized-databases.json', 'human', 1, current_timestamp),
  ('PM-SEC-002', 'pm', 'security-governance', 'Mutating authorized database aliases requires explicit human approval token.', 'pm-console:DbCommand --human-approved', 'human', 1, current_timestamp),
  ('PM-SEC-003', 'policy', 'security-governance', 'Core authenticity payload restore requires two gates: valid decryption key and approved governance event (phase=core_secret_restore).', 'management/tools/restore_core_authenticity.sh;governance_events.phase', 'human', 1, current_timestamp),
  ('PM-SEC-004', 'policy', 'security-governance', 'Plaintext core authenticity payload must not persist on disk after protection; encrypted artifact + metadata are canonical at rest.', 'management/tools/protect_core_authenticity.sh;policy/authenticity/index.json', 'human', 1, current_timestamp),
  ('PM-REC-001', 'pm', 'recovery-governance', 'Recovery-doctor local checkpoints must be retained with bounded count to prevent unbounded workspace growth.', 'management/tools/recovery_doctor.sh#RECOVERY_CHECKPOINT_RETENTION_COUNT', 'human', 1, current_timestamp),
  ('PM-REC-002', 'pm', 'recovery-governance', 'Recovery baseline refresh may be skipped only via explicit environment flag when preserving a prior checksum baseline is required.', 'management/tools/recovery_doctor.sh#RECOVERY_SKIP_BASELINE_REFRESH', 'human', 1, current_timestamp),
  ('PM-ACTION-001', 'pm', 'action-governance', 'Human prompts that imply actionable work must be ingested into action_items and reported via management/pm/reports/action-items.json.', 'build.gradle:actionInboxIngest;build.gradle:actionItemsReport', 'human', 1, current_timestamp),
  ('PM-ACTION-002', 'pm', 'action-governance', 'Action items should link to decision IDs for traceable execution sequencing.', 'pm-tools:StateDatabaseTool/action_item_decision_links', 'human', 1, current_timestamp),
  ('PM-ACTION-003', 'pm', 'action-governance', 'PM refresh must publish action owner summary and SLA trend reports for prioritization and drift visibility.', 'build.gradle:actionOwnerSummaryReport;build.gradle:actionSlaTrendReport', 'human', 1, current_timestamp),
  ('PM-REALM-GOV-001', 'application', 'realm-governance', 'Each realm database should publish governance policy exports using realm_policy_catalog report outputs.', 'build.gradle:applicationRealmPolicyReport', 'human', 1, current_timestamp),
  ('PM-REALM-GOV-002', 'pm', 'realm-governance', 'Each realm database should publish governance policy exports using realm_policy_catalog report outputs.', 'build.gradle:pmRealmPolicyReport', 'human', 1, current_timestamp),
  ('PM-REALM-GOV-003', 'boilerplate', 'realm-governance', 'Each realm database should publish governance policy exports using realm_policy_catalog report outputs.', 'build.gradle:boilerplateRealmPolicyReport', 'human', 1, current_timestamp),
  ('PM-CORE-001', 'pm', 'core-derivative-governance', 'pzAiCore is the base environment arbiter and derivative projects must inherit its authority hierarchy.', 'management/docs/CORE_DERIVATIVE_MODEL.md', 'human', 1, current_timestamp),
  ('PM-CORE-002', 'pm', 'core-derivative-governance', 'Derivative projects must publish machine-readable core/project topology and core-link contracts.', 'management/pm/workflow/core-derivative-topology.json', 'human', 1, current_timestamp),
  ('PM-CORE-003', 'pm', 'core-derivative-governance', 'Implemented workstream knowledge must be distilled into distributed SQLite stores segmented by owner realm with secured write contracts.', 'management/tools/workstream_knowledge_distill.py;build.gradle:workstreamKnowledgeDistill', 'human', 1, current_timestamp),
  ('PM-CORE-004', 'pm', 'core-derivative-governance', 'Core/project/product derivation chains must preserve policy/management/product realm lineage at each inheritance layer.', 'management/pm/workflow/core-derivative-topology.json;management/tools/workstream_knowledge_distill.py', 'human', 1, current_timestamp),
  ('PM-CORE-005', 'pm', 'workstream-governance', 'Workstream identity is immutable (`workstream_uid`) while label/rank are mutable for reprioritization without lineage loss.', 'management/docs/project-plan-progress.csv;pm-tools:StateDatabaseTool/syncProgress', 'human', 1, current_timestamp);

insert into pm_data_dictionary(object_name, object_type, realm, definition, source_ref, naming_pattern, updated_at) values
  ('product_descriptions', 'table', 'pm', 'Canonical core/derivative product registry with hierarchy and role metadata.', 'management/pm/state/project-state.sqlite', 'snake_case', current_timestamp),
  ('issues', 'table', 'pm', 'Issue log records loaded from management/docs/issues-log.csv for governance tickle/effectiveness workflows.', 'pm-tools:StateDatabaseTool/initProjectSchema', 'snake_case', current_timestamp),
  ('plan_tasks', 'table', 'pm', 'Project plan task rows loaded from management/docs/project-plan-progress.csv.', 'pm-tools:StateDatabaseTool/initProjectSchema', 'snake_case', current_timestamp),
  ('workstreams', 'table', 'pm', 'Immutable workstream registry keyed by workstream_uid with mutable labels and priority ranks.', 'pm-tools:StateDatabaseTool/initProjectSchema', 'snake_case', current_timestamp),
  ('governance_events', 'table', 'pm', 'Policy/governance event history loaded from management/docs/policy-governance-events.csv.', 'pm-tools:StateDatabaseTool/initProjectSchema', 'snake_case', current_timestamp),
  ('repo_vcs_snapshot', 'table', 'pm', 'Repository-level VCS state mirror (head/branch/dirty counts).', 'pm-tools:StateDatabaseTool/initProjectSchema', 'snake_case', current_timestamp),
  ('repo_file_state', 'table', 'pm', 'Per-path repository state mirror used for file-discipline reporting.', 'pm-tools:StateDatabaseTool/initProjectSchema', 'snake_case', current_timestamp),
  ('policy_rule_catalog', 'table', 'pm', 'SQL-backed mutable policy rule catalog exported to management/pm/reports/policy-rules.json.', 'management/pm/policy/policy-rule-tables.sql', 'snake_case', current_timestamp),
  ('pm_data_dictionary', 'table', 'pm', 'Data dictionary of PM governance/state objects and naming conventions.', 'management/pm/policy/policy-rule-tables.sql', 'snake_case', current_timestamp),
  ('code_files', 'table', 'pm', 'Realm-scoped file index for SQL-managed code search and traceability.', 'pm-tools:StateDatabaseTool/initCodeIndexSchema', 'snake_case', current_timestamp),
  ('code_file_content', 'table', 'pm', 'Canonical realm-managed source content for SQL-first materialization to filesystem endpoints.', 'pm-tools:StateDatabaseTool/initCodeIndexSchema', 'snake_case', current_timestamp),
  ('code_tokens', 'table', 'pm', 'Token postings list mapping indexed tokens to files and occurrence counts.', 'pm-tools:StateDatabaseTool/initCodeIndexSchema', 'snake_case', current_timestamp),
  ('token_dictionary', 'table', 'pm', 'Realm-scoped token dictionary derived from indexed source files for keyword swatch search.', 'pm-tools:StateDatabaseTool/initCodeIndexSchema', 'snake_case', current_timestamp),
  ('decision_log', 'table', 'pm', 'Realm-local prioritized decision ledger with scope granularity and impact scoring for smallest-change/biggest-reward execution.', 'pm-tools:StateDatabaseTool/initCodeIndexSchema', 'snake_case', current_timestamp),
  ('decision_dependency', 'table', 'pm', 'Dependency edges between decisions in the same realm database.', 'pm-tools:StateDatabaseTool/initCodeIndexSchema', 'snake_case', current_timestamp),
  ('knowledge_entries', 'table', 'pm', 'Knowledge base entries that capture reasoning context, outcomes, and change references for decisions.', 'pm-tools:StateDatabaseTool/initProjectSchema', 'snake_case', current_timestamp),
  ('knowledge_evidence', 'table', 'pm', 'Artifact evidence linked to knowledge entries with path, hash, and capture metadata.', 'pm-tools:StateDatabaseTool/initProjectSchema', 'snake_case', current_timestamp),
  ('knowledge_decision_links', 'table', 'pm', 'Cross-reference map linking knowledge entries to decision IDs across realms.', 'pm-tools:StateDatabaseTool/initProjectSchema', 'snake_case', current_timestamp),
  ('realm_knowledge_sync_report', 'report', 'pm', 'Cross-realm knowledge mirroring diagnostics showing per-realm knowledge/evidence/link counts and decision-link resolution.', 'management/tools/realm_knowledge_sync.py', 'snake_case', current_timestamp),
  ('realm_knowledge_link_gate_report', 'report', 'pm', 'Knowledge link gate status report showing unresolved per-realm decision references with warn/fail semantics.', 'management/tools/realm_knowledge_link_gate.py', 'snake_case', current_timestamp),
  ('environment_health_report', 'report', 'pm', 'Environment readiness report including daemon state, visible session telemetry, and duplicate-session diagnostics.', 'management/tools/environment_health_check.py', 'snake_case', current_timestamp),
  ('pm_console_stale_cleanup_report', 'report', 'pm', 'Stale session detection/cleanup report with warning threshold and consecutive-cycle signals.', 'management/tools/pm_console_cleanup.py', 'snake_case', current_timestamp),
  ('pm_console_stale_history', 'state_file', 'pm', 'History of stale session counts used for warning threshold evaluation across cycles.', 'management/tools/pm_console_cleanup.py --history', 'snake_case', current_timestamp),
  ('environment_dashboard_report', 'report', 'pm', 'Compact triage report for environment readiness, visibility, stale-session warning, and policy threshold context.', 'management/tools/environment_dashboard_report.py', 'snake_case', current_timestamp),
  ('human_readable_ref', 'presentation_pattern', 'pm', 'Human-friendly reference format for presentation outputs: <what> | <YYYY-MM-DD> | #<occurrence>.', 'pm-tools:StateDatabaseTool/humanReadableRef', 'title_case_pipe', current_timestamp),
  ('release_name', 'presentation_field', 'pm', 'Human-friendly release label emitted in management/pm/reports/version.json.', 'build.gradle:versionStamp', 'title_case', current_timestamp),
  ('identifier_registry', 'table', 'pm', 'Cross-discipline persisted identifier ledger (project/policy/version-control/code) including human-readable references.', 'pm-tools:StateDatabaseTool/initProjectSchema', 'snake_case', current_timestamp),
  ('identifier_registry_report', 'report', 'pm', 'Audit export of all persisted identifiers generated to management/pm/reports/identifier-registry.json.', 'build.gradle:identifierRegistryReport', 'snake_case', current_timestamp),
  ('action_items', 'table', 'pm', 'Actionable work ledger with status/priority and optional knowledge/decision linkage.', 'pm-tools:StateDatabaseTool/initProjectSchema', 'snake_case', current_timestamp),
  ('action_item_decision_links', 'table', 'pm', 'Links action items to one or more decision IDs for traceable execution.', 'pm-tools:StateDatabaseTool/initProjectSchema', 'snake_case', current_timestamp),
  ('action_inbox_events', 'table', 'pm', 'Deduplicated event capture for prompt-derived action ingestion.', 'pm-tools:StateDatabaseTool/initProjectSchema', 'snake_case', current_timestamp),
  ('action_owner_summary_report', 'report', 'pm', 'Owner-centric action rollup exported to management/pm/reports/action-owner-summary.json.', 'management/tools/action_owner_summary.py', 'snake_case', current_timestamp),
  ('action_sla_trend_report', 'report', 'pm', 'Rolling SLA breach trend exported to management/pm/reports/action-sla-trend.json with history under management/pm/state/action-sla-history.json.', 'management/tools/action_sla_trend.py', 'snake_case', current_timestamp),
  ('realm_policy_catalog', 'table', 'pm', 'Realm-local governance rules exported from each realm database for governance visibility.', 'pm-tools:StateDatabaseTool/initCodeIndexSchema', 'snake_case', current_timestamp),
  ('experience_events', 'table', 'pm', 'Empirical reasoning event store derived from knowledge outcomes and decision link counts.', 'management/tools/reasoning_sync.py', 'snake_case', current_timestamp),
  ('heuristic_scores', 'table', 'pm', 'Derived heuristic scores computed from experience events for prioritization guidance.', 'management/tools/reasoning_sync.py', 'snake_case', current_timestamp),
  ('derived_insights', 'table', 'pm', 'Second-order insights synthesized from experience heuristics and support signals.', 'management/tools/reasoning_sync.py', 'snake_case', current_timestamp),
  ('insight_edges', 'table', 'pm', 'Directed relationships between derived insights for traceable reasoning chains.', 'management/tools/reasoning_sync.py', 'snake_case', current_timestamp),
  ('pm_workflow_manifest', 'manifest', 'pm', 'Normalized PM workflow phase/adapter mapping manifest.', 'management/pm/workflow/workflow-manifest.json', 'snake_case', current_timestamp),
  ('pm_workflow_phase_task_map', 'adapter_map', 'pm', 'Gradle adapter phaseTaskMap binding phase IDs to executable task lists.', 'management/pm/workflow/workflow-manifest.json#adapters.gradle.phaseTaskMap', 'snake_case', current_timestamp),
  ('pm_workflow_defaults', 'adapter_defaults', 'pm', 'Default workflow phase selection for normalized PM execution.', 'management/pm/workflow/workflow-manifest.json#defaults', 'snake_case', current_timestamp),
  ('core_derivative_topology', 'contract', 'pm', 'Machine-readable hierarchy and link contract between pzAiCore and derivative project realms.', 'management/pm/workflow/core-derivative-topology.json', 'snake_case', current_timestamp),
  ('core_realm_state', 'database', 'pm', 'Distributed core realm state store for lineage and distilled workstream knowledge.', 'management/pm/state/core-realm.sqlite', 'snake_case', current_timestamp),
  ('realm_derivation_nodes', 'table', 'pm', 'Realm derivation graph nodes capturing core->project->product lineage boundaries.', 'management/tools/workstream_knowledge_distill.py', 'snake_case', current_timestamp),
  ('realm_derivation_edges', 'table', 'pm', 'Realm derivation graph edges describing inheritance/manifest relationships.', 'management/tools/workstream_knowledge_distill.py', 'snake_case', current_timestamp),
  ('workstream_knowledge', 'table', 'pm', 'Secured workstream task knowledge rows distilled from plan_tasks and segmented by owner realm.', 'management/tools/workstream_knowledge_distill.py', 'snake_case', current_timestamp),
  ('workstream_rollup', 'table', 'pm', 'Per-workstream completion rollups computed from distilled workstream knowledge rows.', 'management/tools/workstream_knowledge_distill.py', 'snake_case', current_timestamp),
  ('workstream_knowledge_sync_report', 'report', 'pm', 'Distributed workstream distillation report across core/application/management/pm/boilerplate SQLite stores.', 'management/pm/reports/workstream-knowledge-sync.json', 'snake_case', current_timestamp),
  ('core_authenticity_payload_encrypted', 'artifact', 'policy', 'Encrypted core authenticity payload at rest.', 'policy/authenticity/lead-developer-mission-token-20260220T013131Z.json.enc', 'snake_case', current_timestamp),
  ('core_authenticity_payload_metadata', 'artifact', 'policy', 'Integrity and gate-policy metadata for encrypted core authenticity payload.', 'policy/authenticity/lead-developer-mission-token-20260220T013131Z.json.enc.meta.json', 'snake_case', current_timestamp),
  ('core_derivative_bootstrap', 'script', 'pm', 'Bootstrap helper for instantiating new derivative projects from pzAiCore.', 'management/tools/bootstrap_core_derivative_project.sh', 'snake_case', current_timestamp),
  ('package_candidates', 'table', 'boilerplate', 'Boilerplate update package candidate registry synced from product/boilerplate/update-packages.', 'pm-tools:StateDatabaseTool/initBoilerplateSchema', 'snake_case', current_timestamp),
  ('package_files', 'table', 'boilerplate', 'Per-package file inventory for boilerplate payload audit/reporting.', 'pm-tools:StateDatabaseTool/initBoilerplateSchema', 'snake_case', current_timestamp);
